#!/usr/bin/env ruby
require 'rubygems'
require 'daemons/rails/config'

logger = Logger.new "#{root}/log/amqp-daemon.log"
logger.debug '--- Started deposit_coin_ctl'
config = Daemons::Rails::Config.for_controller(File.expand_path(__FILE__))

config[:app_name] = 'peatio:amqp:deposit_coin'
config[:script]   = "#{File.expand_path('../amqp_daemon.rb', __FILE__)}"
config[:ARGV]     = ARGV + %w(-- deposit_coin deposit_coin_address)

Daemons::Rails.run config[:script], config.to_hash
